### ISSUE TITLE
Audio tracks are not dumped correctly

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#198]
Audio tracks are not dumped correctly.

Each drive reads audio sectors with a small handful of samples of offset that should be accounted for.

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audio tracks not dumped correctly](https://trello.com/c/kXNB3TKt/20-audio-tracks-not-dumped-correctly)

**Comment by SilasLaspada** [comment]
I believe that this was fixed in the CD code rewrite.

**Comment by claunia** [comment]
Fixed in 242ee9146672e0988ef08362117d5abfc9359dba
