### ISSUE TITLE
Verbose output for compare command is missing whitespace

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#206]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

There is a visual issue with the verbose output of the compare command that causes it to be hard to read due to missing whitespace. If the end of each row could be aligned, it would be much more readable, and probably look much better as a whole.

![compare](https://user-images.githubusercontent.com/24215969/48919985-53c64880-ee53-11e8-90ec-cae11237d1c8.PNG)

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Verbose output for compare command does not have the correct alignment](https://trello.com/c/ndpJ1p6y/18-verbose-output-for-compare-command-does-not-have-the-correct-alignment)
