### ISSUE TITLE
Add command line switch for privacy mode.

### ISSUE THREAD

**Issue by mrpijey** [aaru-dps/Aaru#213]
Add a command line option to exclude all complete folder references to DiscImageChef tool, dumped images etc. For example, any references to "C:\Users\mrpijey\Documents\MyDisc.iso" should be replaced with just "MyDisc.iso", same goes for references where DiscImageChef is installed where the full path is included.

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add privacy option that does not store paths in any place.](https://trello.com/c/yA6YSvdm/15-add-privacy-option-that-does-not-store-paths-in-any-place)
