### ISSUE TITLE
Redirect DONATIONS.md to NEEDED.md

### ISSUE THREAD

**Issue by nbacon0** [aaru-dps/Aaru#237]
Currently https://github.com/discimagechef/DiscImageChef/blob/master/DONATING.md goes to a 404 Not Found page: would it be possible to redirect it to https://github.com/discimagechef/DiscImageChef/blob/master/NEEDED.md ?

A number of people still have the DONATIONS.md links as their primary resource for looking at the list of drives.

**Comment by claunia** [comment]
github does not have a support for automatic redirection
