### ISSUE TITLE
Allow to specify number of cylinders etc. when converting raw HDD

### ISSUE THREAD

**Issue by FakeShemp** [aaru-dps/Aaru#250]
### Description

When converting a raw HDD image it'd be nice if I could specify the number of cylinders, heads, sectors per track and bits per sector the image has in the command line.

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow custom CHS when converting image](https://trello.com/c/EhaG7rxD/9-allow-custom-chs-when-converting-image)
