### ISSUE TITLE
DIC does not extract files from DICF image

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#263]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running DiscImageChef under Windows 10...
* [X] ...in 64-bit

### Description

Trying to extract the files from a DICF image results in the error "Error reading file: Object reference not set to an instance of an object." Dumping and extracting as ISO does work, but there are issues with that too. Full logs of dumping the disc as DICF and ISO, trying to extract the images, and comparing them are here: https://pastebin.com/AuKum4QR. Link to the image files themselves: https://drive.google.com/file/d/1lXlhV-EUVrSg-ceKi0xI7t5OAdGWvH9_/view?usp=sharing

### Exact command line used:

`dotnet .\DiscImageChef.dll extract-files .\Sony.dicf Sony`

### Output of command execution with debug output enabled
```
DiscImageChef 4.5.99.1693-86deddee built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2019 Natalia Portillo

Image format identified by DiscImageChef format.
Uploading statistics
1 partitions found.

Partition 0:
Identifying filesystem on partition
Error reading file: Object reference not set to an instance of an object.
```

**Comment by SilasLaspada** [comment]
Bug seems to be in the code for extracting files and doesn't seem to be an issue with DICF images themselves. I can extract the files from a CUE image with no problem, and compare says that the DICF and CUE images don't differ, so it seems it's how extract is reading the DICF images that's the problem.

**Comment by claunia** [comment]
Is the drive connected to the ASMedia or the JMicron controller?

**Comment by claunia** [comment]
I see in the report you only have one drive, that's PATA, and one PATA controller, the JMicron.

The JMicron controller has the software raid drivers installed.

We don't, and probably will never, support this configuration. Please uninstall JMicron drivers and use standard ATA drivers included with your version of Windows.

In case this is not possible you'll have to use a different controller whose drivers are provided by Microsoft.
