### ISSUE TITLE
Plextor freezes on reading MCN and ISRC values

### ISSUE THREAD

**Issue by mnadareski** [aaru-dps/Aaru#275]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running DiscImageChef under Windows 10 10.0.17763.771 (64-bit)
* [ ] I was running DiscImageChef under Linux [version here]...
* [ ] I was running DiscImageChef under FreeBSD [version here]...
* [ ] I was running DiscImageChef under macOS [version here]...
* [ ] ...using .NET Framework [version here]...
* [X] ...using .NET Core 2.0
* [ ] ...using Mono [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit

### Description

When dumping a mixed-mode disc (1 data track, 1+ audio tracks on the same apparent session) using a Plextor PX-W5224A, the code hangs indefinitely when reading the MCN and ISRC values. If manually skipped at the SCSI command send level, discs will dump only the data track and then error out on reading the audio tracks.

### Exact command line used:

`DiscImageChef --debug true --verbose true media dump --force true --first-pregap true --fix-offset true --retry-passes 20 --subchannel none --speed 48 \\?\F: DUKE_3D_CD.dicf`

### Expected behavior:
Expected disc to dump with no issues and produce an output file that contains both data and audio tracks

### Actual behavior:
Program freezes until either killed or drive is disconnected

### If command was expected to work with a device fill this out:

Manufacturer: PLEXTOR
Model: CD-R   PX-W5224A
Firmware revision: 1.04
Device type: SCSI (connected via USB IDE adapter)
    
### Output of command execution with debug output enabled

(Of note, on newest build, debug flag enabled does NOT seem to output debug logging to file. The log attached here was generated using the `--debug true` flag, as seen above.)

[DUKE_3D_CD.zip](https://github.com/discimagechef/DiscImageChef/files/4155375/DUKE_3D_CD.zip)

**Comment by mnadareski** [comment]
On request, here is the log from VS2 where the MCN and ISRC reads were manually skipped.

[VS2.zip](https://github.com/discimagechef/DiscImageChef/files/4155479/VS2.zip)

**Comment by mnadareski** [comment]
Also as requested, here are the logs when MCN and ISRC reads are manually skipped and debug output is enabled for DUKE_3D_CD.

[DUKE_3D_CD.zip](https://github.com/discimagechef/DiscImageChef/files/4156109/DUKE_3D_CD.zip)

**Comment by claunia** [comment]
Fixed in fb947e3d5ca4ba9a49a6bca6c9c6e7f671ef1985 and e3f70ae7a415bb0c5f59c9a515fcdf5abe115522.
