### ISSUE TITLE
Unknown error code 1 when running commands that use devices

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#287]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit

### Description

Trying to run any command that uses a device stops with "Unknown error code 1", other commands seem to be unaffected.

### Output of command execution with debug output enabled
```
Aaru 4.5.99.2020-18db5ed8 built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2020 Natalia Portillo

DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=G:
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --fix-offset=True
DEBUG (Dump-Media command): --force=True
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --metadata=True
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --output=test.iso
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --trim=True
DEBUG (Dump-Media command): --verbose=False
DEBUG (Dump-Media command): --subchannel=any
DEBUG (Dump-Media command): Parsed options:
DEBUG (ATA Device): IDENTIFY DEVICE took 2.1659 ms.
Unknown error code 1
```

**Comment by claunia** [comment]
You need to run using Administrator privileges.

**Comment by claunia** [comment]
Please attach export from msinfo32.

**Comment by SilasLaspada** [comment]
Alright, here you go!
[msinfo32.zip](https://github.com/aaru-dps/Aaru/files/4284875/msinfo32.zip)

**Comment by claunia** [comment]
I see in the report you only have one drive, that's PATA, and one PATA controller, the JMicron.

The JMicron controller has the software raid drivers installed.

We don't, and probably will never, support this configuration. Please uninstall JMicron drivers and use standard ATA drivers included with your version of Windows.

In case this is not possible you'll have to use a different controller whose drivers are provided by Microsoft.
