### ISSUE TITLE
"Uploading statistics" shows in command window inconsistently

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#296]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

"Uploading statistics" is printed to the command window inconsistently when running commands, sometimes it's one of the first lines and sometimes it's printed between other lines.

**Comment by claunia** [comment]
It is done on purpose in the debug compilation.
