### ISSUE TITLE
Typos in device info

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#311]
When running device info, Aaru reports whether or not a drive supports “assymetrical access” instead of “asymmetrical access”. Another issue is that when a disc isn’t inserted, it says “Medium is No disc inserted, tray closed or caddy inserted”, which is worded weirdly to me, but there might not be a way to reasonably fix this.

**Comment by claunia** [comment]
"No disc inserted, tray closed or caddy inserted" is literally what the specification says that value means, that's why "medium" (value) is etc
