### ISSUE TITLE
[QUESTION] Does Aaru identify Photo CDs as such or just as CD-R/CD-ROM?

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#321]
I have a few CDs I've burned that I suspect should be valid Portfolio Photo CDs are only recognized as CD-R (or CD-ROM if the drive masks CD-R), so does Aaru identify Photo CDs and Portfolio Photo CDs as anything other than the base media type?

**Comment by claunia** [comment]
It does not identify PCDs.

**Comment by claunia** [comment]
Fixed in c069073d1986cb8a8ea129b91908ebf32306decd
