### ISSUE TITLE
[QUESTION] Are Portfolio Photo CDs fundamentally different from a normal Photo CD?

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#322]
Are Portfolio Photo CDs fundamentally different from a normal Photo CD, are they an extension to a normal Photo CD but not fundamentally different, or are they just a fancy name for a specific type of Photo CD?

**Comment by claunia** [comment]
Attach one Portfolio CD so I can check.

**Comment by SilasLaspada** [comment]
Here you go! [Portfolio.zip](https://github.com/aaru-dps/Aaru/files/4357573/Portfolio.zip)

**Comment by claunia** [comment]
No they aren't.
