### ISSUE TITLE
[QUESTION] Are Photo CDs that are created by me the same as ones created by Kodak?

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#323]
Are Photo CDs created by me (using Kodak Build-It) the same as the ones originally created by Kodak? As in, did they use CD-R as well, or did they actually use pressed discs so that they would be CD-ROM?

**Comment by claunia** [comment]
Kodak photo laboratories used CD-R. CD-ROM were used for pressed professional stock photos or projects ordered en masse.
