### ISSUE TITLE
[QUESTION] Is there any available software to create Kodak Photo CD scripts (SCP files) other than ScriptMaker?

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#324]
ScriptMaker seems to only allow me to create Portfolio Photo CDs projects, is there any software out there that would allow me to create scripts compatible with Kodak CD Builder that would let me create normal Photo CDs?

**Comment by claunia** [comment]
I don't know and its out of the scope of this issue tracker.
