### ISSUE TITLE
[Device Report] LiteOn DH-4O1S CP56

### ISSUE THREAD

**Issue by MrKagami** [aaru-dps/Aaru#335]
### Prerequisites

* [5.0.0.2879] Are you running the latest version?
* [ ] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [ X] I was running Aaru under Windows [version here]...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under FreeBSD [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...using .NET Framework [version here]...
* [ ] ...using .NET Core [version here]...
* [ ] ...using Mono [version here]...
* [ ] ...in 32-bit
* [X ] ...in 64-bit

### Description

Attached is a new Drive Report für LITE-ON DH-4O1S. unfortunately there is a strange behavior of CDs with reading Subchannels with C2 pointers (maybe a loop or it takes really long), so I couldn't test this. I will test it with your debug version when I have more time.

Currently only DVD-ROM, BD-ROM, PS3-DVD, PS4-DVD is verified and in the logfile.

[ATAPI_BD  O  DH4O1S_CP56.zip](https://github.com/aaru-dps/Aaru/files/4475109/ATAPI_BD.O.DH4O1S_CP56.zip)

Could anyone tell me an good allround PATA/SATA USB-Adapter which does work in the most cases? I had a second adapter and AARU couldn't detect the drive name correctly. I think it's a problem of the usb-adapter.

**Comment by claunia** [comment]
Hi,

USB to ATA/SATA adapters have the problem of modifying and limiting the commands. While most of the times the only harmful effects are reporting a wrong name or blocking some commands that Aaru doesn't use, device reports are useless when done using them, so I have to reject it until you can do it directly attached to an ATA controller.

Also it is recommended to use Linux to create the device reports for now, as there are some issues with doing them on Windows that may not have a fix. You can use any Linux boot cd for that purpose.

**Comment by mirh** [comment]
Do the same possible limitations apply to "native" external USB drives?
