### ISSUE TITLE
Daemon Tools Lite and Alcohol 120% unable to mount CCD image created by Aaru

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#348]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit

### Description

Daemon Tools Lite and Alcohol 120% are unable to mount a CCD image created by Aaru, and are able to mount one of the same disc created by Clone CD itself. The CCD files themselves are different, with Aaru being marked as version 2 instead of version 3, and Clone CD having sections dedicated to each track at the end that Aaru is missing completely. Otherwise, the CCD's seem to be identical. Renaming Clone CD's CCD file to replace Aaru's CCD file allows Daemon Tools and Alcohol to mount the image file successfully, so this issue seems to only be related to the CCD files. Files (CDG.ccd is from Aaru, IMAGE.ccd is from Clone CD): [CCD.zip](https://github.com/aaru-dps/Aaru/files/4498695/CCD.zip)

**Comment by claunia** [comment]
@SilasLaspada I think this is fixed in the latest commits today please re-check and close?

Version 3 is different but still it should be able to open Version 2 discs created by Aaru now.

**Comment by SilasLaspada** [comment]
Fixed as of the latest commit. Converting an old aaruf image to ccd now makes an image that is mounted by A120% and DAEMON Tools Lite, and the mounted image is able to be read as CDG by Kareoke software.
