### ISSUE TITLE
Device Reports ATAPI_BD  O  DH4O1S_CP56 & YAMAHA_CRW-F1E_1.0g

### ISSUE THREAD

**Issue by MrKagami** [aaru-dps/Aaru#350]
Attached two new device reports created with Linux and without USB adapter.

[Device Reports.zip](https://github.com/aaru-dps/Aaru/files/4510976/Device.Reports.zip)

How can I recognize and set the write offsets for CD-Audio ?

I always get the message:
**Drive reading offset is 120 bytes (30 samples).                                                                                                                                                                                              
Disc write offset is unknown, dump may not be correct.**

**Comment by claunia** [comment]
Hi,

The reports are inserted in the database, update and it should stop showing you the message. If you get other of the media you didnt try in this device report you can do it again and I'll join the results.

As for write offsets for Audio CD, there is no known way, if even possible at all (very possibly not) to recognize it. The current method is to use a data track on the same disc to calculate it, so discs that lack a data track cannot have it fixed, only the read offset is.
