### ISSUE TITLE
DAEMON Tools Lite unable to mount CUE created by Aaru due to ISRC line

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#383]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit

### Description

DAEMON Tools Lite doesn't recognize a cue of a CDDA created by Aaru when trying to mount it. It is able to mount a cue image created by ImgBurn, and is able to mount a cue image of a CDROM created by Aaru. This may be a bug on DAMON's end, but should be looked into anyway to be on the safe side. Log and cue files: [audio.zip](https://github.com/aaru-dps/Aaru/files/4971068/audio.zip)

**Comment by SilasLaspada** [comment]
Also happens with cue image of a CD-i disc.

**Comment by SilasLaspada** [comment]
The bin file of the audio CD created by aaru has different sectors compared to the one created by ImgBurn, I'll upload the image files ASAP.

**Comment by SilasLaspada** [comment]
Retried, and also happens with an image of a CD-ROM. I identified the problem as being the line that says ISRC in the image, removing this line allows both Alcohol 120% and Daemon Tools Lite to mount the image.

**Comment by claunia** [comment]
Fixed by 1198af2
