### ISSUE TITLE
Device report for PIONEER DVR-112D

### ISSUE THREAD

**Issue by jonasrosland** [aaru-dps/Aaru#394]
### Prerequisites

* [ ] Are you running the latest version?
* [ ] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows [5.1.99]...
* [X] ...in 64-bit

### Description

Device report for PIONEER DVR-112D, included as devices for the Bravopro Xi2 disc publisher

### Exact command line used:

`aaru dev report f:`

[PIONEER_DVD-RW  DVR-112D_9.15.json.zip](https://github.com/aaru-dps/Aaru/files/4982284/PIONEER_DVD-RW.DVR-112D_9.15.json.zip)

**Comment by claunia** [comment]
Done, you can update the database.
