### ISSUE TITLE
Aaru claims Plextor 755SA does not support GigaRec

### ISSUE THREAD

**Issue by RibShark** [aaru-dps/Aaru#405]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Windows 10 2004
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under FreeBSD [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...using .NET Framework [version here]...
* [ ] ...using .NET Core [version here]...
* [ ] ...using Mono [version here]...
* [ ] ...in 32-bit
* [ ] ...in 64-bit

### Description

When checking device information in Aaru, for the Plextor 755SA GigaRec is listed as unsupported despite being supported by the drive.

### Exact command line used:
GUI used.

### Expected behavior:
GigaRec should be marked as supported.

### Actual behavior:
GigaRec is marked as not supported.

### If command was expected to work with a device fill this out:

* **Manufacturer**: Plextor
* **Model**: 755SA
* **Bus**:
    * [ ] Parallel ATA
    * [x] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
    * [ ] MultiMediaCard

**Comment by RibShark** [comment]
Requested files.
[plextor_755sa.zip](https://github.com/aaru-dps/Aaru/files/5076694/plextor_755sa.zip)

**Comment by claunia** [comment]
Can you confirm if it says it is supported in the command line?

**Comment by claunia** [comment]
> Protected commands and the PX-755/760
> Plextor does obviously not tolerate that anyone can use the unique functions of the PX-755/760 drive on Linux or other "alternative" operating systems, or that anyone uses alternative applications on Windows. Plextor has introduced "protected commands" into these drives. Commands like enabling/disabling GigaREC or SilentMode, as well as all quality check commands, now require to retrieve a code and send another one that is calculated from the received one back to the drive, otherwise those commands will be rejected by the drive. Please note that I have bought the drive to find out what means Plextor is using in order to force people into using PlexTools, and even to force people into using Windows.
From https://www.alexander-noe.com/cdvd/px/index.php

See also https://qpxtool.sourceforge.io/problems.html (firmware links dead).

Closed as firmware lockdown by manufacturer.
Command output is correct.

**Comment by RibShark** [comment]
> 
> 
> > Protected commands and the PX-755/760
> > Plextor does obviously not tolerate that anyone can use the unique functions of the PX-755/760 drive on Linux or other "alternative" operating systems, or that anyone uses alternative applications on Windows. Plextor has introduced "protected commands" into these drives. Commands like enabling/disabling GigaREC or SilentMode, as well as all quality check commands, now require to retrieve a code and send another one that is calculated from the received one back to the drive, otherwise those commands will be rejected by the drive. Please note that I have bought the drive to find out what means Plextor is using in order to force people into using PlexTools, and even to force people into using Windows.
> > From https://www.alexander-noe.com/cdvd/px/index.php
> 
> See also https://qpxtool.sourceforge.io/problems.html (firmware links dead).
> 
> Closed as firmware lockdown by manufacturer.
> Command output is correct.

I am using unlocked firmware that reenables the commands. I can't test with the latest Aaru build due to #425.

**Comment by claunia** [comment]
Me and @SilasLaspada checked and the command is send correctly, and returns correctly the value in other drives, but not on the 755 and 760.

We then checked qpxtool and wodim and they return not supported as well.

I checked both cdrkit and qpxtool source code and they are using the same command.

If you want to reverse engineer how PlexTools sends the command, I will implement that, but for a merely aesthetical indicator, that fails only on a single model of drives, due to manufacturer locking, I will not start to reverse engineer it.

**Comment by RibShark** [comment]
> 
> 
> Me and @SilasLaspada checked and the command is send correctly, and returns correctly the value in other drives, but not on the 755 and 760.
> 
> We then checked qpxtool and wodim and they return not supported as well.
> 
> I checked both cdrkit and qpxtool source code and they are using the same command.
> 
> If you want to reverse engineer how PlexTools sends the command, I will implement that, but for a merely aesthetical indicator, that fails only on a single model of drives, due to manufacturer locking, I will not start to reverse engineer it.

QpxTool returns supported for me, I am using unlocked firmware.
