### ISSUE TITLE
Unexpected unreadable sectors when dumping mixed mode CD

### ISSUE THREAD

**Issue by fallenoak** [aaru-dps/Aaru#406]
### Prerequisites

* [x] Are you running the latest version?

### Check and fill as appropriate:
* [x] I was running Aaru under Windows 10...
* [x] ...in 64-bit

### Description

I'm attempting to dump a disc, CD-ROM Today Disc 1 (from 1994). The disc appears to be mixed mode, with 1 data track and 10 audio tracks. The disc appears to be in good physical shape, but it's possible some subtle physical flaw exists.

The disc can be dumped without errors using a recent version of Sarami's DIC, but Aaru 5.1.0 indicates `34175 sectors could not be read`.

### Exact command line used:

`m dump --speed 8 --options "compress=false" "\\?\H:" <path here>`

### Expected behavior:

Since DiscImageCreator dumped the disc without indicating unreadable sectors, I expected Aaru to do the same.

### Actual behavior:

`34175 sectors could not be read`

### If command was expected to work with a device fill this out:

* **Manufacturer**: Plextor
* **Model**: PX-W4824TA
    
### Output of command execution

```
aaru 5.1.0.3214
Copyright c 2011-2020 Natalia Portillo

Output image format: Aaru Format.
Device in database since 7/26/2020 5:18:31 AM.

Checking if drive supports PQ subchannel reading...
Checking if drive supports full raw subchannel reading...
Full raw subchannel reading supported...
Drive returns subchannel in BCD...
Reading full TOC
Building track map...
Calculating pregaps, can take some time...
Reading ATIP
Reading Disc Information
Reading PMA
Reading Session Information
Reading CD-Text from Lead-In
Solving lead-outs...
Detecting disc type...
Checking mode for track 1...
Track 1 is MODE1
Reading 16 sectors at a time.
Device reports 315578 blocks (772534944 bytes).
Device can read 16 blocks at a time.
Device reports 2448 bytes per logical block.
SCSI device type: MultiMediaDevice.
Media identified as CD.
Setting flags for track 1...
Setting flags for track 2...
Setting flags for track 3...
Setting flags for track 4...
Setting flags for track 5...
Setting flags for track 6...
Setting flags for track 7...
Setting flags for track 8...
Setting flags for track 9...
Setting flags for track 10...
Setting flags for track 11...
Drive reading offset is 392 bytes (98 samples).
Disc offsets is 0 bytes (0 samples)
Setting speed to 8x.
Setting index 1 for track 1 to LBA 0.
Reading sector 315195 of 315578 (0.984 MiB/sec.)
Dump finished in 469.8118151 seconds.
Average dump speed 1677.693 KiB/sec.
Average write speed 54352.367 KiB/sec.
Trimming skipped sectors
Pregap for track 2 set to 149 sectors.
Trimming sector 315577
Trimming finished in 5.0883098 seconds.
Retrying sector 315577, pass 5, forward

Retrying sector 315577 subchannel, pass 5, forward
Closing output file.
Closed in 2.5821041 seconds.
Hashing image file...
Hashing image file byte 580911104 of 581065052
Hashing media tags...
Checking filesystems
Hashing tracks...
Hashings sector 281088 of 281399
Hashings subchannel sector 281088 of 281399
Hashings sector 1536 of 1605
Hashings subchannel sector 1536 of 1605
Hashings sector 2560 of 2904
Hashings subchannel sector 2560 of 2904
Hashings sector 1024 of 1192
Hashings subchannel sector 1024 of 1192
Hashings sector 6656 of 6996
Hashings subchannel sector 6656 of 6996
Hashings sector 4096 of 4284
Hashings subchannel sector 4096 of 4284
Hashings sector 1024 of 1400
Hashings subchannel sector 1024 of 1400
Hashings sector 2560 of 2888
Hashings subchannel sector 2560 of 2888
Hashings sector 1024 of 1280
Hashings subchannel sector 1024 of 1280
Hashings sector 6144 of 6402
Hashings subchannel sector 6144 of 6402
Hashings sector 5120 of 5228
Hashings subchannel sector 5120 of 5228

Writing metadata sidecar

Took a total of 576.831 seconds (453.666 processing commands, 33.960 checksumming, 13.880 writing, 2.582 closing).
Average speed: 1.624 MiB/sec.
Fastest speed burst: 1.449 MiB/sec.
Slowest speed burst: 0.031 MiB/sec.
34175 sectors could not be read.
36082 subchannels could not be read.
```

**Comment by claunia** [comment]
Please attach the resume file.

**Comment by claunia** [comment]
@fallenoak after investigating I've found the problem comes from the USB to ATAPI bridge you're using.

I would need to know the exact chip (you'll need to open it) to fix the problem.

As an interim I suggest trying to resume the dump to see if it reads the sectors it couldn't correctly, or connecting the drive to a non-RAID, in-motherboard ATA controller.

Moving out of milestones until I can get the problematic hardware myself.

**Comment by fallenoak** [comment]
Thanks @claunia! I'll crack open the bridge and see what's inside, and look into an alternative set up. If you'd like, I can mail you an identical bridge. I have several lying about.

**Comment by claunia** [comment]
@fallenoak sending me one will be helpful.

Would it be possible you try it in a Linux computer in the meantime? To have all sides covered.

**Comment by claunia** [comment]
I got another use with the same problem using a multisession data CD.

**Comment by SilasLaspada** [comment]
I am able to reproduce the issue on my own adapter. 

Aaru output from dump: [406.zip](https://github.com/aaru-dps/Aaru/files/5629351/406.zip)

Media info: https://pastebin.com/7gSEBG40
