### ISSUE TITLE
GitHub: Add `hacktoberfest` topic to the repo

### ISSUE THREAD

**Issue by darkstar** [aaru-dps/Aaru#413]
Since DigitalOcean changed Hacktoberfest to be [opt-in now](https://hacktoberfest.digitalocean.com/hacktoberfest-update) we should probably add the `hacktoberfest` topic to Aaru.

I don't think spam-PRs will be a problem for Aaru (they are only a problem for much higher-profile repos)

**Comment by claunia** [comment]
Done
