### ISSUE TITLE
Allow calling dlls directly

### ISSUE THREAD

**Issue by Dimensional** [aaru-dps/Aaru#462]
Allow the calling of certain dlls directly instead of calling through aaru.exe/dll. Can allow for users to trim down packaged copies of the program and leave in only files required for the specific functions, such as checksumming only, or converting an image, or extracting a filesystem.

### Check and fill as appropriate:
* [✓?] New command...
* [✓?] Improvement to output...

## Detailed Description
Can there be an update to allow for directly calling dlls and associated ones? For example, allowing us to run ```dotnet Aaru.Images.dll``` to verify or even convert an image files without needing to call ```aaru.exe``` or ```dotnet aaru.dll``` with the associated commands.

## Context

The biggest benefit I can see from this would be to allow 3rd party programs, mainly those that aren't programmed in C# or any of the .NET supported languages, to pass a call straight to the dll to execute a command. This would allow these 3rd party programs to possibly package precompiled versions of the software, and even only include the bare minimum required for the dll they want, even more so if the dll could be built with all the dependencies statically built into it. Programs such as RetroArch, ePSXe, PCSX2, etc might benefit from this only as supported external dlls.

This might also benefit 3rd party C# programs too, as they wouldn't have to copy certain calls from the aaru.exe/dll source or need to include the program as well, just pass a command via the .NET CLR to the dlls. This would even allow DICUI to call the dlls directly instead of having to include all files, including aaru.exe/dll, again trimming down the overall size of the package.

**Comment by claunia** [comment]
Programs that are not in .NET supported languages cannot directly call .NET libraries, as they need the .NET JIT/CLR to run.

The different libraries in Aaru depend only on the needed libraries, you can extract and use them separately, as long as you comply with each separate library license. The horsepower of the application is in Aaru.Core, separate from the two interfaces (CLI and GUI) already, but its functionality (verifying, converting, dumping) will not be moved to the lower level libraries (images, filesystems, filters, types).

You can use Aaru.Images as long as you comply with the dependencies, that is not the whole project. Obviously you cannot use an Image without the CommonTypes, or the Filters, etc, etc.

DICUI includes the whole Aaru and calls in the command line by @mnadareski choice, not by my design.

In the future the different Aaru libraries may be offered as NuGet packages, after the planned 6.0 refactoring. However you can still call them separately, as indicated before.
