### ISSUE TITLE
[Feature Request] Add support for the Ashbak image format

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#464]
### Check and fill as appropriate:
* [X] Support for a new media image format...
* [ ] Support for identifying a new filesystem...
* [ ] Support for extracting files from a new filesystem...
* [ ] New command...
* [ ] Improvement to output...
* [ ] Other...

## Detailed Description

Add support for Ashampoo Burning Studio's Ashbak format.

## Context

Allow users to access another image format using Aaru.

## Known documentation

Images have been created using various options, and an image using every possible combination of options has (in theory) been made. These options include compression, password protection (the password for every image that uses one is 12345), and file splitting. The images are all zipped up here: [464.zip](https://github.com/aaru-dps/Aaru/files/5587030/464.zip)

**Comment by claunia** [comment]
No plans to add support for backup formats yet. But pull requests are welcome if using IArchive interface.
