### ISSUE TITLE
[CloneCD] Invalid image size calculating from disc with data in track 1 pregap.

### ISSUE THREAD

**Issue by claunia** [aaru-dps/Aaru#489]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [x] I was running Aaru under Linux 5.9.14-arch1-1...
* [x] ...in 64-bit
* [x] ...using an Intel / AMD processor
    * **Image format**: CloneCD
    * **Application that created the image**: CloneCD
* [x] I was checksumming the image

### Description

Invalid image size calculating from disc with data in track 1 pregap.

### Exact command line used:

Unit test.

### Expected behavior:

Test pass.

### Actual behavior:

Invalid number of sectors.

### Output of command execution with debug output enabled
```
Sectors: cdiready_theapprentice.ccd
  Expected: 279300
  But was:  210150
```

### Image
cdiready_theapprentice.ccd

**Comment by SilasLaspada** [comment]
I dumped a disc with the same characteristics in aaruformat and then converted to clonecd and it generates an invalid image.
