### ISSUE TITLE
Media scan doesn't properly run with an HD-DVD

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#516]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* **Device manufacturer**: Toshiba
* **Model**: DVD/HD  X807616
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [X] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [ ] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [X] I was scanning media (disk, tape, etc)...

### Description

When running media scan on an HD-DVD, it speeds through the disc at 1000 MiB/sec, and then reports that either every or the vast majority of sectors are bad. There are no bad sectors when dumping the disc.

### Exact command line used:

`Aaru [command] [parameters]`

### Output of command execution with debug output enabled
```
aaru 5.2.99.3380-alpha+cce0a874 built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2021 Natalia Portillo

Using SCSI READ (10) command.
Media has 6358272 blocks of 2048 bytes/each. (for a total of 12.127 GiB)
Reading 64 sectors at a time.
Reading sector 6358208 of 6358272 (1040.292 MiB/sec.)
```

### Media details

HD-DVD movie - Firewall

**Comment by FakeShemp** [comment]
https://github.com/aaru-dps/Aaru/blob/4784a6c101c60ce9d4c413d3bc5f742d6a510280/Aaru.Core/Devices/Scanning/SCSI.cs#L280

Blu-rays and HDDVDs don't like to read 64 blocks at a time. Changing this to 32 solves the issue.
