### ISSUE TITLE
Device report TSSTcorp BDDVDW SE-506BB TS00 (MT1956)

### ISSUE THREAD

**Issue by paulyc** [aaru-dps/Aaru#543]
Duly in re: Device not in database, please create a device report and attach it to a Github issue.
[TSSTcorp_BDDVDW SE-506BB_TS00.json.txt](https://github.com/aaru-dps/Aaru/files/5973345/TSSTcorp_BDDVDW.SE-506BB_TS00.json.txt)

USB reports mfr. and model MediaTek Inc. MT1956
Stock firmware. There is a TS01 revision, but it don't seem broke, so I ain't 'fixing' it;)

**Comment by paulyc** [comment]
Ran it again with MediaTek vendor command F1h subcommand 06h. Don't have any rewritable media on hand to test (I gave up on rewritable optical media somewhere around 4x CD-RW)
[TSSTcorp_BDDVDW SE-506BB_TS00.json.txt](https://github.com/aaru-dps/Aaru/files/5974137/TSSTcorp_BDDVDW.SE-506BB_TS00.json.txt)

**Comment by claunia** [comment]
Report added to database, please update.
