### ISSUE TITLE
[ISO9660] "Error reading file: The filename, directory name, or volume label syntax is incorrect." extracting filesystem from image using Amiga CD encoding

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#601]
### Prerequisites

* [ ] Are you running the latest version?
* [ ] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
    * **Image format**: Multiple  
    * **Application that created the image**: Aaru
* [ ] I was converting the image...
    * ...**Destination image format**:
* [ ] I was listing the filesystem contents...
* [X] I was extracting the filesystem contents...
    * ...**Filesystem**: ISO9660
    * [X] Analyze command recognizes the filesystem
* [ ] I was creating a metadata sidecar
* [ ] I was checksumming the image
* [ ] I was verifying the image

### Description

When extracting the filesystem from a CD image created for the Amiga CD, Aaru mid-extraction stops with the error "Error reading file: The filename, directory name, or volume label syntax is incorrect.". When viewing the ISO through archive.org, it seems to render the text correctly. Example of how the folder name appears in Windows Explorer:
![explorer_hyJVmDB36E](https://user-images.githubusercontent.com/24215969/120878070-49827a80-c577-11eb-9a45-d0d2feacbf53.png)

### Exact command line used:

`aaru fs extract .\NetworkCD.aaruf 0`

### Output of command execution with debug output enabled
https://pastebin.com/u5QkN62w

### Image

https://archive.org/details/simple-networking-tools-for-amiga-cd-weird-science-1994

**Comment by claunia** [comment]
That's not a correct ISO name.

The folder is named "ESPAÑOL" with bytes 0x45 0x53 0x50 0x41 0xD1 0x4F 0x4C that corresponds to Windows-1252 codepage that violates the ISO9660 standard.

When there's not a Joliet extension the codepage used is ASCII where the byte 0xD1 is not defined and therefore gets converted to ? a character not supported in Windows for filenames.

You should set up the namespace as Romeo, then it will work (default codepage for Romeo is Windows-1252 so you don't need to specify it.)
