### ISSUE TITLE
[CD-i Ready] Media scan reports unreadable sectors not present in dump

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#602]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: ASUS
* **Model**: BW-16D1HT
* **Bus**:
    * [ ] Parallel ATA
    * [X] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [ ] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [X] I was scanning media (disk, tape, etc)...

### Description

When scanning a CD-i Ready disc, Aaru reports bad sectors that aren't reported during a dump.

### Exact command line used:

`aaru m scan E:`

### Output of command execution with debug output enabled
```
Reading sector 144736 of 292322 (0.604 MiB/sec.)DEBUG (SCSI Device): READ CD (LBA: 144736, Block Size: 2352, Transfer Length: 32, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: True, Last Error: 0) took 5693.6849 ms.
DEBUG (Media-Scan): READ CD error:
SCSI SENSE: MEDIUM ERROR
L-EC UNCORRECTABLE ERROR

Reading sector 144768 of 292322 (0.011 MiB/sec.)DEBUG (SCSI Device): READ CD (LBA: 144768, Block Size: 2352, Transfer Length: 32, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: True, Last Error: 0) took 3442.399 ms.
DEBUG (Media-Scan): READ CD error:
SCSI SENSE: MEDIUM ERROR
L-EC UNCORRECTABLE ERROR
```

**Comment by claunia** [comment]
Media scan will test if the area between the hidden data track and the audio track is readable by the drive.
Media dump will skip it automatically if unreadable.

Works as expected.
