### ISSUE TITLE
Aaru incorrectly 0's out some sectors in some multi-track CDs

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#603]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: ASUS
* **Model**: BW-16D1HT
* **Bus**:
    * [ ] Parallel ATA
    * [X] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [X] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [ ] I was scanning media (disk, tape, etc)...

### Description

When dumping a CD with multiple tracks (one data and one audio), Aaru's dump doesn't match DIC's right at the start of the second track (which is audio). These sectors are mostly 0'd out in Aaru's dump, but contain data in DIC's dump. I believe other CDs are affected as well, but I would have to go through them to be sure.

Image sector contents: https://pastebin.com/XUtFwYpG

Media info:
```aaru 5.2.99.3380-alpha+6011991c built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2021 Natalia Portillo

Media has 341061 blocks of 2048 bytes/each. (for a total of 666.135 MiB)
TOC:
First track number in first complete session: 1
Last track number in last complete session: 2
Track number: 1
Track starts at LBA 0, or MSF 00:00:00
Q subchannel stores track pointer
Data track, recorded uninterrupted
Digital copy of track is prohibited

Track number: 2
Track starts at LBA 287812, or MSF 64:04:00
Q subchannel stores track pointer
Stereo audio track with no pre-emphasis
Digital copy of track is prohibited

Track number: Lead-Out
Track starts at LBA 341061, or MSF 34:05:00
Q subchannel stores track pointer
Stereo audio track with no pre-emphasis
Digital copy of track is prohibited


Standard Disc Information:
Disc type declared as CD-DA or CD-ROM
Disc is finalized
Last session is complete
First track on disc is track 1
Disc has 1 sessions
First track in last session is track 1
Last track in last session is track 2
Last session Lead-In address is 4294967295 (as LBA) or FF:FF:FF
Last possible Lead-Out address is 4294967295 (as LBA) or FF:FF:FF
Disc is defined for restricted use

Session information:
First complete session number: 1
Last complete session number: 1
First track number in last complete session: 1
Track starts at LBA 512, or MSF 02:00:00
Data track, recorded uninterrupted
Digital copy of track is prohibited


Raw TOC:
First complete session number: 1
Last complete session number: 1
Session 1
First track number: 1 (Data track, recorded uninterrupted)
Disc type: 0
Last track number: 2 (Stereo audio track with no pre-emphasis)
Lead-out start position: 75:49:36
Lead-out is audio type
Data track 1 starts at: 00:02:00 (Data track, recorded uninterrupted)
Audio track 2 starts at: 63:59:37 (Stereo audio track with no pre-emphasis)

Media Serial Number:
Media identified as CD

Track calculations:
Track 1 starts at LBA 0, ends at LBA 287659, has a pregap of 0 sectors and is of type Data
Track 2 starts at LBA 287660, ends at LBA 341060, has a pregap of 152 sectors and is of type Audio

Offsets:
Drive reading offset is 24 bytes (6 samples).
Combined offset is -24 bytes (-6 samples)
Disc offset is -48 bytes (-12 samples)
```

[603 media info.zip](https://github.com/aaru-dps/Aaru/files/6605658/603.media.info.zip)

### Media details

[603.zip](https://github.com/aaru-dps/Aaru/files/6605652/603.zip)

**Comment by SilasLaspada** [comment]
Still present as of newest commit.

**Comment by claunia** [comment]
Fixed in 7c384310f02d1f0f0f533432d48d34b04ffa0e95.

**Comment by claunia** [comment]
Broken in 5.3rc1

**Comment by claunia** [comment]
Don't know why it's reopened, it's fixed.
