### ISSUE TITLE
Device Report - Asus SBW-06D2X-U

### ISSUE THREAD

**Issue by TheDankstoneMemery** [aaru-dps/Aaru#614]
[Drive report.txt](https://github.com/aaru-dps/Aaru/files/6679791/Drive.report.txt)
Running Aaru 5.2 on Windows 10 x64 build 21H1.
Edit: Added json file as text since pastebin doesn't seem to be displaying the file publicly.

https://pastebin.com/S7PS704J

**Comment by claunia** [comment]
Partial report added to database, CD-R must not contain audio tracks, thanks.
