### ISSUE TITLE
[Alcohol 120%] MDS image created from Raw ISO image has significantly fewer sectors than the original image

### ISSUE THREAD

**Issue by SilasLaspada** [aaru-dps/Aaru#624]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [ ] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
    * **Image format**:  Raw ISO image
    * **Application that created the image**: Aaru
* [X] I was converting the image...
    * ...**Destination image format**: Alcohol 120%
* [ ] I was listing the filesystem contents...
* [ ] I was extracting the filesystem contents...
    * ...**Filesystem**:
    * [ ] Analyze command recognizes the filesystem
* [ ] I was creating a metadata sidecar
* [ ] I was checksumming the image
* [ ] I was verifying the image

### Description

An MDS image created from converting a raw ISO image has significantly fewer sectors than the original image.

### Exact command line used:

`i compare .\LNE100TX_V5_12.iso .\LNE100TX_V5_12.mds`

### Output of command execution with debug output enabled
```
aaru 5.2.99.3380-alpha+869a6dff built by DESKTOP-8B4K7NM in Debug, modified
Copyright c 2011-2021 Natalia Portillo

Input file 1 format identified by Raw Disk Image.
Input file 2 format identified by Alcohol 120% Media Descriptor Structure.
Comparing disk image characteristics
Comparing sectors...
Comparing sector 464 of 464...
Disc image 1: .\LNE100TX_V5_12.iso
Disc image 2: .\LNE100TX_V5_12.mds
Image sectors differ
Image 1 has more sectors
Images differ
```

### Image

https://we.tl/t-axQBoCVf0o

**Comment by claunia** [comment]
In the end it comes from the fact that ISO is 2048 bps only and Alcohol is 2352 bps only and convert was not catching and stopping no this problem, it would now do, so I'll close this as that feature is not planned before 6.0.
