### ISSUE TITLE
[FAT] Diskcopy 6.5 DMF and MF2DDfail unit test failure

### ISSUE THREAD

**Issue by TheRogueArchivist** [aaru-dps/Aaru#637]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [ ] I was running Aaru under Windows [version here]...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [ ] ...in 64-bit
* [ ] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
    * **Image format**:  
    * **Application that created the image**:
* [ ] I was converting the image...
    * ...**Destination image format**:
* [ ] I was listing the filesystem contents...
* [X] I was extracting the filesystem contents...
    * ...**Filesystem**: FAT16
    * [ ] Analyze command recognizes the filesystem
* [ ] I was creating a metadata sidecar
* [ ] I was checksumming the image
* [ ] I was verifying the image

### Description

Null reference exception when getting cluster of last directory in directory depth as created by fstester.
Stacktrace: 
[message(1).txt](https://github.com/aaru-dps/Aaru/files/6805200/message.1.txt)

### Exact command line used:

`Aaru [command] [parameters]`

### Output of command execution with debug output enabled
```
Paste the whole output of the executed command when you append '-d' to your command line parameters here
```

**Comment by claunia** [comment]
Fixed in 840cdcc331d28f0fbc3e07f43a877d7874e09060
