### ISSUE TITLE
[Feature Request] Dynamic allocation for Virtual PC

### ISSUE THREAD

**Issue by TheRogueArchivist** [aaru-dps/Aaru#645]
### Check and fill as appropriate:
* [ ] Support for a new media image format...
* [ ] Support for identifying a new filesystem...
* [ ] Support for extracting files from a new filesystem...
* [ ] New command...
* [ ] Improvement to output...
* [X] Other...

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[VirtualPC disk image] Support writing sparse images](https://trello.com/c/D1RRdkcq/83-virtualpc-disk-image-support-writing-sparse-images)
